// strings.ts: mobile-only EN/ES strings (tabs, headers, hints, stamps, reason codes, profile).
import type { Lang } from "./types";

/** Mobile-only strings. Shared wording comes from ./i18n (copied from the web app unchanged). */
const en = {
  appIntro: "Look up a sample address and a date. See the rental rules in the public record, the reason for each result and the original source.",
  tabHome: "Home",
  tabSearch: "Search",
  tabChanges: "Changes",
  tabMethod: "Method",
  change: "Change",
  close: "Close",
  done: "Done",
  back: "Back",
  clear: "Clear search",
  dateTitle: "Choose a date",
  selected: "Selected",
  sampleCount: (n: number) => `${n} sample addresses from the project data. Nothing outside this set can be looked up.`,
  searchTitle: "Find an address",
  noInfo: "No information available in the record",
  ruleDetails: "Rule details",
  retrievedOn: (d: string) => `Retrieved ${d}`,
  evaluation: "Evaluation",
  evalNone: "Not available for this date",
  evalNoneBody: (status: string, date: string) => `The rule's legal status is "${status}", but no result was precomputed for ${date}.`,
  openDatePicker: "Opens the date picker",
  addressDetails: "Address details",
  scenarioDetails: "Scenario details",
  resUnavailShort: "No result exists for this scenario yet, so a count can't be confirmed. This is not zero.",
  tapToOpen: "Double-tap to show the full section",
  searchSub: "Search the sample set by ID, street or city.",
  loadingTitle: "Opening the public record…",
  howTitle: "How the system works",
  dataTitle: "Data used",
  rulesFor: "Rules on record",
  evidence: "View source evidence",
  sourceEvidence: "Source evidence",
  auditDetails: "Sources, dates and audit details",
  exemptions: "Exemptions",
  notInferred: "Missing facts are not inferred.",
  why: "Why this result",
  loadFriendly: "We couldn't load the sample data. Try again.",
  howSummary: "Rules come from public documents; a fixed engine computes each result.",
  moreSteps: "More about the method",
  details: "Details",
  property: "Property",
  openRule: "Open rule",
  noMatchShort: "Only the 500 sample addresses can be searched. Try an ID (A0036) or part of a street name.",
  dateNoResults: "No precomputed results",
  dateHasResults: "Results precomputed",
  dateFooter: "Only dates listed in the data can be chosen. The app never computes results.",
  noFactsTitle: "Building facts missing",
  noFactsBody: "Some facts are not in the record. Rules that depend on them stay unknown; nothing is filled in.",
  noRulesTitle: "No applicable rules",
  conflict: "Conflict flagged — needs human review",
  displacedReason: "Reason for displacement",
  usesFixturesNo: "Real submission data (no fixtures).",
  usesFixturesYes: "Fixture data is active.",
  limitsTitle: "Limits",
  openExternal: "Opens the original document in the browser.",
  categories: (n: number) => `${n} categor${n === 1 ? "y" : "ies"}`,
  rulesN: (n: number) => `${n} rule${n === 1 ? "" : "s"}`,
  matchesFirst: (n: number) => `showing the first ${n}`,
  tryTitle: "Try a tricky one",
  tryMismatch: "Postal city isn't the law",
  tryNeighborhood: "Neighborhood, city rules",
  tryConflict: "State and local rules clash",
  stampTitle: "Case file",
  stampEarned: "Stamp earned",
  stampProgress: (k: number, n: number) => `${k} of ${n} stamps`,
  stampDone: "Case closed — you explored every angle.",
  stampHint: "Explore to collect stamps. Nothing is stored.",
  stamp: { find: "Find an address", mismatch: "Spot a jurisdiction mismatch", source: "Read a source", time: "Travel in time", scenario: "Explore a scenario" } as Record<string, string>,
  stampHow: { find: "Open any address", mismatch: "Open one where postal city ≠ legal jurisdiction", source: "Open a rule's source evidence", time: "Change the as-of date", scenario: "Open a change test" } as Record<string, string>,
  filterAll: "All",
  filterHint: "Double-tap to show only these rules",
  reasons: {
    missing_units: "Unit count not in the record",
    missing_year_built: "Year built not in the record",
    small_owner_exemption_unresolved: "Small-landlord exemption can't be checked (owner not in the record)",
    effective_date_contradiction: "Sources disagree on the effective date",
    bars_local_rent_control: "State law bars local rent control here",
    cutoff_year_ambiguous: "Built in the cutoff year; the exact date is needed",
  } as Record<string, string>,
  displacedBy: (r: string) => `Displaced by ${r}`,
  affectedHere: "addresses affected",
  addressesShort: "addresses",
  conflictsHere: "need human review",
  jumpTo: (d: string) => `View at ${d}`,
  testNotFound: "This change test is not in the record.",
  profile: "You",
  profileOpen: "Opens your profile and settings",
  settings: "Settings",
  langLabel: "Language",
  langBody: "Set from your phone's language. Change it here any time.",
  hapticsLabel: "Haptics",
  hapticsBody: "Gentle vibration when you tap, pick or earn a stamp.",
  motionLabel: "Reduce motion",
  motionBody: "Turns off stamps, fades and count-ups. Follows your system setting too.",
  resetStamps: "Reset case file",
  sessionOnly: "Settings last for this session. No account, no personal data.",
  dataAsOf: (d: string) => `Data generated ${d}`,
  approxStreet: "Approximate location · about 150 m",
  approxArea: "Approximate · city area only",
  mapAffected: "Affected",
  mapFlagged: "Needs review",
  mapOther: "Not affected",
  mapHint: "Tap a dot to open that address.",
  byCity: "Affected addresses by jurisdiction",
  ofTotal: (v: number, t: number) => `${v} of ${t}`,
  beforeAfter: (r: string) => `Before → after · ${r}`,
  kpiRules: "rules extracted",
  kpiDocs: "source documents",
  kpiAddresses: "sample addresses",
  kpiDates: "lookup dates",
  glance: "At a glance",
  rulesByCategory: "Rules by category",
  resultsAt: (d: string) => `Every result on ${d}`,
  tapSegment: "Tap a segment to name it.",
};

const es: typeof en = {
  appIntro: "Consulta una dirección de muestra y una fecha. Ve las reglas de alquiler del registro público, el motivo de cada resultado y la fuente original.",
  tabHome: "Inicio",
  tabSearch: "Buscar",
  tabChanges: "Cambios",
  tabMethod: "Método",
  change: "Cambiar",
  close: "Cerrar",
  done: "Listo",
  back: "Atrás",
  clear: "Borrar búsqueda",
  dateTitle: "Elegir fecha",
  selected: "Seleccionada",
  sampleCount: (n: number) => `${n} direcciones de muestra de los datos del proyecto. No se puede consultar nada fuera de este conjunto.`,
  searchTitle: "Buscar una dirección",
  noInfo: "No hay información disponible en el registro",
  ruleDetails: "Detalle de regla",
  retrievedOn: (d: string) => `Recuperado el ${d}`,
  evaluation: "Evaluación",
  evalNone: "No disponible para esta fecha",
  evalNoneBody: (status: string, date: string) => `El estado legal de la regla es "${status}", pero no hay resultado precalculado para el ${date}.`,
  openDatePicker: "Abre el selector de fecha",
  addressDetails: "Detalle de dirección",
  scenarioDetails: "Detalle de escenario",
  resUnavailShort: "Aún no hay resultado para este escenario, así que no se puede confirmar un conteo. No equivale a cero.",
  tapToOpen: "Toca dos veces para ver la sección completa",
  searchSub: "Busca en el conjunto de muestra por ID, calle o ciudad.",
  loadingTitle: "Abriendo el registro público…",
  howTitle: "Cómo funciona el sistema",
  dataTitle: "Datos usados",
  rulesFor: "Reglas en el registro",
  evidence: "Ver evidencia de la fuente",
  sourceEvidence: "Evidencia de la fuente",
  auditDetails: "Fuentes, fechas y detalles de auditoría",
  exemptions: "Exenciones",
  notInferred: "Los datos faltantes no se infieren.",
  why: "Por qué este resultado",
  loadFriendly: "No pudimos cargar los datos de muestra. Inténtalo de nuevo.",
  howSummary: "Las reglas vienen de documentos públicos; un motor fijo calcula cada resultado.",
  moreSteps: "Más sobre el método",
  details: "Detalles",
  property: "Inmueble",
  openRule: "Abrir regla",
  noMatchShort: "Solo se pueden buscar las 500 direcciones de muestra. Prueba un ID (A0036) o parte del nombre de la calle.",
  dateNoResults: "Sin resultados precalculados",
  dateHasResults: "Resultados precalculados",
  dateFooter: "Solo se pueden elegir fechas que figuran en los datos. La app nunca calcula resultados.",
  noFactsTitle: "Faltan datos del edificio",
  noFactsBody: "Algunos datos no constan en el registro. Las reglas que dependen de ellos quedan como unknown; no se rellena nada.",
  noRulesTitle: "Sin reglas aplicables",
  conflict: "Conflicto marcado — necesita revisión humana",
  displacedReason: "Motivo del desplazamiento",
  usesFixturesNo: "Datos reales de la entrega (sin fixtures).",
  usesFixturesYes: "Hay datos de prueba (fixtures) activos.",
  limitsTitle: "Límites",
  openExternal: "Abre el documento original en el navegador.",
  categories: (n: number) => `${n} categoría${n === 1 ? "" : "s"}`,
  rulesN: (n: number) => `${n} regla${n === 1 ? "" : "s"}`,
  matchesFirst: (n: number) => `se muestran las primeras ${n}`,
  tryTitle: "Prueba un caso difícil",
  tryMismatch: "La ciudad postal no es la ley",
  tryNeighborhood: "Barrio, reglas de la ciudad",
  tryConflict: "Choque entre reglas estatales y locales",
  stampTitle: "Expediente",
  stampEarned: "Sello obtenido",
  stampProgress: (k: number, n: number) => `${k} de ${n} sellos`,
  stampDone: "Caso cerrado: exploraste todos los ángulos.",
  stampHint: "Explora para reunir sellos. No se guarda nada.",
  stamp: { find: "Encontrar una dirección", mismatch: "Detectar otra jurisdicción", source: "Leer una fuente", time: "Viajar en el tiempo", scenario: "Explorar un escenario" } as Record<string, string>,
  stampHow: { find: "Abre cualquier dirección", mismatch: "Abre una donde la ciudad postal ≠ jurisdicción legal", source: "Abre la evidencia de una regla", time: "Cambia la fecha de consulta", scenario: "Abre una prueba de cambio" } as Record<string, string>,
  filterAll: "Todas",
  filterHint: "Toca dos veces para ver solo estas reglas",
  reasons: {
    missing_units: "El número de unidades no consta en el registro",
    missing_year_built: "El año de construcción no consta en el registro",
    small_owner_exemption_unresolved: "No se puede verificar la exención de pequeño propietario (el dueño no consta)",
    effective_date_contradiction: "Las fuentes no coinciden en la fecha de vigencia",
    bars_local_rent_control: "La ley estatal prohíbe aquí el control local de rentas",
    cutoff_year_ambiguous: "Construido en el año de corte; se necesita la fecha exacta",
  } as Record<string, string>,
  displacedBy: (r: string) => `Desplazada por ${r}`,
  affectedHere: "direcciones afectadas",
  addressesShort: "direcciones",
  conflictsHere: "requieren revisión humana",
  jumpTo: (d: string) => `Ver al ${d}`,
  testNotFound: "Esta prueba de cambio no está en el registro.",
  profile: "Tú",
  profileOpen: "Abre tu perfil y ajustes",
  settings: "Ajustes",
  langLabel: "Idioma",
  langBody: "Tomado del idioma de tu teléfono. Cámbialo aquí cuando quieras.",
  hapticsLabel: "Vibración",
  hapticsBody: "Vibración suave al tocar, elegir u obtener un sello.",
  motionLabel: "Reducir movimiento",
  motionBody: "Desactiva sellos, fundidos y conteos animados. También sigue el ajuste del sistema.",
  resetStamps: "Reiniciar expediente",
  sessionOnly: "Los ajustes duran esta sesión. Sin cuenta ni datos personales.",
  dataAsOf: (d: string) => `Datos generados el ${d}`,
  approxStreet: "Ubicación aproximada · unos 150 m",
  approxArea: "Aproximada · solo zona de la ciudad",
  mapAffected: "Afectada",
  mapFlagged: "Requiere revisión",
  mapOther: "No afectada",
  mapHint: "Toca un punto para abrir esa dirección.",
  byCity: "Direcciones afectadas por jurisdicción",
  ofTotal: (v: number, t: number) => `${v} de ${t}`,
  beforeAfter: (r: string) => `Antes → después · ${r}`,
  kpiRules: "reglas extraídas",
  kpiDocs: "documentos fuente",
  kpiAddresses: "direcciones de muestra",
  kpiDates: "fechas consultadas",
  glance: "De un vistazo",
  rulesByCategory: "Reglas por categoría",
  resultsAt: (d: string) => `Todos los resultados al ${d}`,
  tapSegment: "Toca un segmento para ver su nombre.",
};

export const strings = { en, es };
export type MobileStrings = typeof en;
export const m = (lang: Lang): MobileStrings => strings[lang];
