// strings.ts: mobile-only EN/ES strings (tabs, headers, hints).
import type { Lang } from "./types";

/** Mobile-only strings. Shared wording comes from ./i18n (copied from the web app unchanged). */
const en = {
  appIntro: "Look up a sample address and a date. See the rental rules in the public record, the reason for each result and the original source.",
  tabHome: "Home",
  tabSearch: "Search",
  tabChanges: "Changes",
  tabMethod: "Method",
  change: "Change",
  close: "Close",
  done: "Done",
  back: "Back",
  clear: "Clear search",
  dateTitle: "Choose a date",
  selected: "Selected",
  sampleCount: (n: number) => `${n} sample addresses from the project data. Nothing outside this set can be looked up.`,
  searchTitle: "Find an address",
  noInfo: "No information available in the record",
  ruleDetails: "Rule details",
  retrievedOn: (d: string) => `Retrieved ${d}`,
  evaluation: "Evaluation",
  evalNone: "Not available for this date",
  evalNoneBody: (status: string, date: string) => `The rule's legal status is "${status}", but no result was precomputed for ${date}.`,
  openDatePicker: "Opens the date picker",
  addressDetails: "Address details",
  scenarioDetails: "Scenario details",
  resUnavailShort: "No result exists for this scenario yet, so a count can't be confirmed. This is not zero.",
  tapToOpen: "Double-tap to show the full section",
  searchSub: "Search the sample set by ID, street or city.",
  loadingTitle: "Opening the public record…",
  howTitle: "How the system works",
  dataTitle: "Data used",
  rulesFor: "Rules on record",
  evidence: "View source evidence",
  auditDetails: "Sources, dates and audit details",
  exemptions: "Exemptions",
  notInferred: "Missing facts are not inferred.",
  why: "Why this result",
  loadFriendly: "We couldn't load the sample data. Try again.",
  howSummary: "Rules come from public documents; a fixed engine computes each result.",
  moreSteps: "More about the method",
  details: "Details",
  property: "Property",
  openRule: "Open rule",
  noMatchShort: "Only the 500 sample addresses can be searched. Try an ID (A0036) or part of a street name.",
  dateNoResults: "No precomputed results",
  dateHasResults: "Results precomputed",
  dateFooter: "Only dates listed in the data can be chosen. The app never computes results.",
  noFactsTitle: "Building facts missing",
  noFactsBody: "Some facts are not in the record. Rules that depend on them stay unknown; nothing is filled in.",
  noRulesTitle: "No applicable rules",
  conflict: "Conflict flagged — needs human review",
  displacedReason: "Reason for displacement",
  usesFixturesNo: "Real submission data (no fixtures).",
  usesFixturesYes: "Fixture data is active.",
  limitsTitle: "Limits",
  openExternal: "Opens the original document in the browser.",
  categories: (n: number) => `${n} categor${n === 1 ? "y" : "ies"}`,
  rulesN: (n: number) => `${n} rule${n === 1 ? "" : "s"}`,
};

const es: typeof en = {
  appIntro: "Consulta una dirección de muestra y una fecha. Ve las reglas de alquiler del registro público, el motivo de cada resultado y la fuente original.",
  tabHome: "Inicio",
  tabSearch: "Buscar",
  tabChanges: "Cambios",
  tabMethod: "Método",
  change: "Cambiar",
  close: "Cerrar",
  done: "Listo",
  back: "Atrás",
  clear: "Borrar búsqueda",
  dateTitle: "Elegir fecha",
  selected: "Seleccionada",
  sampleCount: (n: number) => `${n} direcciones de muestra de los datos del proyecto. No se puede consultar nada fuera de este conjunto.`,
  searchTitle: "Buscar una dirección",
  noInfo: "No hay información disponible en el registro",
  ruleDetails: "Detalle de regla",
  retrievedOn: (d: string) => `Recuperado el ${d}`,
  evaluation: "Evaluación",
  evalNone: "No disponible para esta fecha",
  evalNoneBody: (status: string, date: string) => `El estado legal de la regla es "${status}", pero no hay resultado precalculado para el ${date}.`,
  openDatePicker: "Abre el selector de fecha",
  addressDetails: "Detalle de dirección",
  scenarioDetails: "Detalle de escenario",
  resUnavailShort: "Aún no hay resultado para este escenario, así que no se puede confirmar un conteo. No equivale a cero.",
  tapToOpen: "Toca dos veces para ver la sección completa",
  searchSub: "Busca en el conjunto de muestra por ID, calle o ciudad.",
  loadingTitle: "Abriendo el registro público…",
  howTitle: "Cómo funciona el sistema",
  dataTitle: "Datos usados",
  rulesFor: "Reglas en el registro",
  evidence: "Ver evidencia de la fuente",
  auditDetails: "Fuentes, fechas y detalles de auditoría",
  exemptions: "Exenciones",
  notInferred: "Los datos faltantes no se infieren.",
  why: "Por qué este resultado",
  loadFriendly: "No pudimos cargar los datos de muestra. Inténtalo de nuevo.",
  howSummary: "Las reglas vienen de documentos públicos; un motor fijo calcula cada resultado.",
  moreSteps: "Más sobre el método",
  details: "Detalles",
  property: "Inmueble",
  openRule: "Abrir regla",
  noMatchShort: "Solo se pueden buscar las 500 direcciones de muestra. Prueba un ID (A0036) o parte del nombre de la calle.",
  dateNoResults: "Sin resultados precalculados",
  dateHasResults: "Resultados precalculados",
  dateFooter: "Solo se pueden elegir fechas que figuran en los datos. La app nunca calcula resultados.",
  noFactsTitle: "Faltan datos del edificio",
  noFactsBody: "Algunos datos no constan en el registro. Las reglas que dependen de ellos quedan como unknown; no se rellena nada.",
  noRulesTitle: "Sin reglas aplicables",
  conflict: "Conflicto marcado — necesita revisión humana",
  displacedReason: "Motivo del desplazamiento",
  usesFixturesNo: "Datos reales de la entrega (sin fixtures).",
  usesFixturesYes: "Hay datos de prueba (fixtures) activos.",
  limitsTitle: "Límites",
  openExternal: "Abre el documento original en el navegador.",
  categories: (n: number) => `${n} categoría${n === 1 ? "" : "s"}`,
  rulesN: (n: number) => `${n} regla${n === 1 ? "" : "s"}`,
};

export const strings = { en, es };
export type MobileStrings = typeof en;
export const m = (lang: Lang): MobileStrings => strings[lang];
